monitoring:
  hosts:
    monitoring01:
      ansible_ssh_host: 0.0.0.0

  vars:
    pd_integration_key_high: "yyyyy"
    pd_integration_key_low: "xxxxxx"

    near_rpc:
      - { service: near_rpc, ip: 'near_server:3030', env: prod }

    node_exporter_extra_entries:
      - { service: node_exporter, ip: 'near_server:9100', env: prod }
