monitoring:
  hosts:
    monitoring01:
      ansible_ssh_host: 0.0.0.0

  vars:
    pd_integration_key_high: "yyyyy"
    pd_integration_key_low: "xxxxxx"

    # on near_rpc_url add an rpc node from near (127.0.0.1:3030 is considering that you are running a near node locally)
    near_rpc_url: "http://127.0.0.1:3030"
    near_rpc:
      - { service: near_rpc, ip: 'near_server:3030', env: prod }

    near_exporter:
      - { service: near_exporter, ip: 'near_server:8080', env: prod }

    near_pool_name:
      mainnet:
       - xxxxx.poolv1.near

    node_exporter_extra_entries:
      - { service: node_exporter, ip: 'near_server:9100', env: prod }

