- name: Restart the Prometheus service
  service:
    name: prometheus
    state: restarted
  listen: event_restart_prometheus

- name: Reload systemd
  command: systemctl daemon-reload
  listen: systemd_reload


- name: Restart node_exporter service
  service:
    name: node_exporter
    state: restarted
    

