- name: Creating alertmanager user group
  group: name="{{alertmanager_groupId}}"
  become: true

- name: Creating alertmanager user
  user:
    name: "{{alertmanager_userId}}"
    group: "{{alertmanager_groupId}}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{alertmanager_userId}} nologin User"
    createhome: "no"
    state: present

- name: Download alertmanager
  unarchive:
    src: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: Copy alertmanager executable to bin
  copy:
    src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64/alertmanager"
    dest: "/usr/local/bin/alertmanager"
    owner: "{{alertmanager_userId}}"
    group: "{{alertmanager_groupId}}"
    remote_src: yes
    mode: 0755

- name: Delete alertmanager tmp folder
  file:
    path: '/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64'
    state: absent

- name: Creates data directory
  file: 
    path: "/data/alertmanager/"
    state: directory
    owner: "{{alertmanager_userId}}"
    group: "{{alertmanager_groupId}}"
    mode: 0755

- name: Creates config directory
  file: 
    path: "/etc/alertmanager/"
    state: directory
    owner: "{{alertmanager_userId}}"
    group: "{{alertmanager_groupId}}"
    mode: 0755

- name: Copy config file
  template:
    src: "alertmanager.yml"
    dest: /etc/alertmanager/alertmanager.yml
    owner: "{{alertmanager_userId}}"
    group: "{{alertmanager_groupId}}"

- name: Copy systemd init file
  template:
    src: alertmanager_init.service.j2
    dest: /etc/systemd/system/alertmanager.service
  notify: systemd_reload

- name: Start alertmanager service
  service:
    name: alertmanager
    state: started
    enabled: yes

- name: Check if alertmanager is accessible
  uri:
    url: http://localhost:9093
    method: GET
    status_code: 200
