---

- name: Install node_exporter
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: Copy node_exporter file to bin
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
#    owner: "{{node_exporter_userId}}"
#    group: "{{node_exporter_groupId}}"
    remote_src: yes
    mode: 0755

- name: Delete node_exporter tmp folder
  file:
    path: '/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64'
    state: absent


# Create services
- name: Copy Node exporter service
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
  notify:
    - Restart node_exporter service

- name: Enable node_exporter service
  systemd:
    name: node_exporter
    enabled: yes
    daemon_reload: yes

- name: restart node_exporter
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: yes
