---
- name: Build near binary on strong server config
  become: yes
  hosts: all
  tasks:
     - name: Recursively remove directory
       file:
         path: /root/nearcore
         state: absent

     - git:
         repo: 'https://github.com/nearprotocol/nearcore.git'
         dest: /root/nearcore
         version: "{{ near_version }}"

     - name: Execute cargo build --release 
       shell: "{{ item }}"
       with_items:
          - export PATH="$HOME/.cargo/bin:$PATH" && cd $HOME/nearcore && cargo build -p neard --release
       register: build

     - debug: 
         var: build

     - name: check near version
       command: /root/nearcore/target/release/neard --version
       register: version

     - debug: var=version.stdout_lines


     - name: Validate version
       shell: >
         [[ "$(/root/nearcore/target/release/neard --version | awk '{print $4 }')" = "{{ near_version }}" ]] || exit 1
       args:
         executable: /bin/bash
       changed_when: no
       ignore_errors: yes

